### ISSUE TITLE
App crash when payment sheet deployed android

### ISSUE THREAD

**Issue by developermvuk** [flutter-stripe/flutter_stripe#1586]
My app is crashing once payment sheet is deployed on android, used to work fine however just as of recent it's causing the app to crash.

**Comment by jonasbark** [comment]
Please stick to the issue template. A lot of information is missing here.

**Comment by developermvuk** [comment]
Here is the error log when the app crashes

E/AndroidRuntime(27580): FATAL EXCEPTION: main
E/AndroidRuntime(27580): Process: com.(app name).(app name), PID: 27580
E/AndroidRuntime(27580): java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
E/AndroidRuntime(27580): 	at android.os.Parcel.createException(Parcel.java:1950)
E/AndroidRuntime(27580): 	at android.os.Parcel.readException(Parcel.java:1918)
E/AndroidRuntime(27580): 	at android.os.Parcel.readException(Parcel.java:1868)
E/AndroidRuntime(27580): 	at m.ays.q(:com.google.android.gms.dynamite_dynamitemodulesc@234914022@23.49.14 (100400-0):172)
E/AndroidRuntime(27580): 	at m.ayp.a(:com.google.android.gms.dynamite_dynamitemodulesc@234914022@23.49.14 (100400-0):14)
E/AndroidRuntime(27580): 	at m.ayr.c(:com.google.android.gms.dynamite_dynamitemodulesc@234914022@23.49.14 (100400-0):7)
E/AndroidRuntime(27580): 	at m.ayk.d(:com.google.android.gms.dynamite_dynamitemodulesc@234914022@23.49.14 (100400-0):7)
E/AndroidRuntime(27580): 	at m.ayl.handleMessage(:com.google.android.gms.dynamite_dynamitemodulesc@234914022@23.49.14 (100400-0):281)
E/AndroidRuntime(27580): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27580): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(27580): 	at android.app.ActivityThread.main(ActivityThread.java:6702)
E/AndroidRuntime(27580): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27580): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(27580): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by developermvuk** [comment]
Please also note the app is only crashing when Google pay is enabled in sheet. If we disable Google Pay the payment sheet will open without crashing the app.

**Comment by remonh87** [comment]
you need to add this to your manifest
```xml
<meta-data
                android:name="com.google.android.gms.wallet.api.enabled"
                android:value="true" />
```
also add following to your app build.gradle:

```
    implementation 'com.google.android.gms:play-services-wallet:19.1.0'

```

**Comment by remonh87** [comment]
I will create a doc for google pay configuration

**Comment by developermvuk** [comment]
> you need to add this to your manifest
> 
> ```
> <meta-data
>                 android:name="com.google.android.gms.wallet.api.enabled"
>                 android:value="true" />
> ```
> 
> also add following to your app build.gradle:
> 
> ```
>     implementation 'com.google.android.gms:play-services-wallet:19.1.0'
> ```

I have added this however still facing the same issue.. any help would be much appreciated.

**Comment by developermvuk** [comment]
This issue is occurs only on android versions 10 and below, hoping a fix can be sorted.

**Comment by remonh87** [comment]
Can you try to run the example app on the same device? I am able to run the paymentsheet with google pay

![Screenshot_1705346580](https://github.com/flutter-stripe/flutter_stripe/assets/20230599/8782c3e4-d531-4182-aec9-5109581fea89)

I really need a proper reporduction scenario to fix this issue else I am inclined to close it.

**Comment by developermvuk** [comment]
> Can you try to run the example app on the same device? I am able to run the paymentsheet on Android 9 with google pay
> 
> ![Screenshot_1705346580](https://private-user-images.githubusercontent.com/20230599/296854077-8782c3e4-d531-4182-aec9-5109581fea89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDk5MDQsIm5iZiI6MTcwNTM0OTYwNCwicGF0aCI6Ii8yMDIzMDU5OS8yOTY4NTQwNzctODc4MmMzZTQtZDUzMS00MTgyLWFlYzktNTEwOTU4MWZlYTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDIwMTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNzRlNDRiNjllMjI0YjNhOTliMmExZWYxMzUzNjAyZDcwYTQxY2Q2N2QzYzUxMTU2NjdmNThmZmZkNWQ1YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zggeG5s1GTFZKdirXhhulxKIeGsKAnoAOqKQ36RCBSY)
> 
> I really need a proper reporduction scenario to fix this issue else I am inclined to close it.

This occurs not in test mode and for android version 10 & under, we have tried on devices running android 11+ and the payment sheet does not cause the app to crash

refer to this also as we found this thread seems to be 'google' issue: https://github.com/stripe/stripe-android/issues/7707

**Comment by remonh87** [comment]
thanks for letting us know the issue. It seems indeed an android  issue. I would recommend using: https://pub.dev/packages/device_info_plus and then do not supply google pay parameters in case the skd < 10 in your app.  I  do not want to provide a fix myself because else we are out of sync with functionality of the official stripe sdk.

**Comment by JlUgia** [comment]
Hi everyone, we are currently rolling out a fix for the issue you are experiencing. Let us know if you are still seeing instances of this exception later this week.

**Comment by dharmendrasinh-concetto** [comment]
Hello @JlUgia, I have checked with flutter_stripe latest version 10.0.0, but issue is not resolved. still experiencing crash with google pay.

**Comment by dmengelt** [comment]
@dharmendrasinh-concetto it has nothing to do with the `flutter_stripe` version. We started rolling out a new Google Play Services version `24.02.12` to include the fix. Rollout should hit 100% this week.

**Comment by remonh87** [comment]
I will close this issue as it has nothing to do with our lib.

**Comment by developermvuk** [comment]
So is this fixed now?

**Comment by dmengelt** [comment]
@developermvuk Yes. We fully rolled out Google Play Services `24.02.12`. This version contains the fix.

**Comment by lokus1980** [comment]
Hello, this functionality still does not work and any of my Android phones in RELEASE mode.

I have tested on multiple phones with Android 10 and Android 14. It always works in Debug mode but crashes instantly in Release mode. Please help.

Flutter: 3.24.0 (latest version)
flutter_stripe: 11.0.0 (latest version)

<img width="310" alt="payment sheet" src="https://github.com/user-attachments/assets/b12b746d-b3f0-4409-8e20-b416b883a382">
<img width="313" alt="android 14" src="https://github.com/user-attachments/assets/4ace30d9-a2af-45d8-8524-7d4cf856cb0b">
<img width="326" alt="device" src="https://github.com/user-attachments/assets/6fe098e9-1776-4010-8fc7-13b8488a2106">

Debug mode (works):
https://github.com/user-attachments/assets/926a1aa2-f7b9-4179-9d1d-6d264e816beb

Release mode (crashes):
https://github.com/user-attachments/assets/b14f3d2e-c294-45f0-bb44-c685b682d978

This blocks me from releasing the app to production as the payment feature is the core functionality here.

Please help.

**Comment by lokus1980** [comment]
> Can you try to run the example app on the same device? I am able to run the paymentsheet on Android 9 with google pay
> 
> ![Screenshot_1705346580](https://private-user-images.githubusercontent.com/20230599/296854077-8782c3e4-d531-4182-aec9-5109581fea89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNjI5NzUsIm5iZiI6MTcyNTA2MjY3NSwicGF0aCI6Ii8yMDIzMDU5OS8yOTY4NTQwNzctODc4MmMzZTQtZDUzMS00MTgyLWFlYzktNTEwOTU4MWZlYTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDAwMDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZTNlNDU1NjVkNjA0NGZmODkxZTExNDY5MGYyYjE4YmQ3MTExMTliMWQ0ZDFmYTAyMGJjNzdiZjgxYjJlOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UaPa05Sv-sqcFucdXALfTIK0k7usMA0tO0gnEPFplkk)
> 
> I really need a proper reporduction scenario to fix this issue else I am inclined to close it.

Did you run it in Debug mode or Release mode?

**Comment by lokus1980** [comment]
@developermvuk - did you manage to fix that issue on your end? I tried so many things and nothing works in Release mode.

**Comment by yashpatel2202** [comment]
Can someone reopen this issue? we still facing the issue in android release mode.
