### ISSUE TITLE
App crashes in android devices when click on back button while entering card details in stripe payment sheet.

### ISSUE THREAD

**Issue by kuldipuniqual** [flutter-stripe/flutter_stripe#1622]
java.lang.NoSuchMethodError: No virtual method getEmojiStart(Ljava/lang/CharSequence;I)I in class Landroidx/emoji2/text/EmojiCompat; or its super classes (declaration of 'androidx.emoji2.text.EmojiCompat' appears in /data/app/~~aOSpTFg5uvWmuOMUdghklg==/com.mobile.maintenanceSOS-PwNSyQ4_O9fe3cu82GTvDw==/base.apk!classes19.dex)

**Comment by kuldipuniqual** [comment]
issue solved in flutter_stirpe version 10.0.0

**Comment by Ronak99** [comment]
It's awesome that the issue is resolved, however, I won't be able to update the dependency version. Can you point me to the change that had to me made?

**Comment by BrijalKothari** [comment]
Not solved getting same error in new version

**Comment by Andrea951112** [comment]
I'm using the 10.1.1 version but this error is still present: 
java.lang.NoSuchMethodError: No virtual method getEmojiStart(Ljava/lang/CharSequence;I)I in class Landroidx/emoji2/text/EmojiCompat; or its super classes (declaration of 'androidx.emoji2.text.EmojiCompat'
