### ISSUE TITLE
Card details not Complete on Andriod

### ISSUE THREAD

**Issue by phawadshah** [flutter-stripe/flutter_stripe#2005]
**Describe the bug**
Creating Payment Method from Card on Andriod throws "Card details not complete". The below code works perfect on ios. I get the card details from the customer using card form field and then create payment method and then confirm payment method, it throws exception "incomplete card details" on the andriod.

**To Reproduce**
1. Use CardFormField and enter any testing card number
2. Create Payment Method from the card
3. StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null))

// ------ CARD FORM FIELD.

        CardFormField(
          controller: controller,
          onCardChanged:(){},
          autofocus: true,
          onFocus: (cardFocus) {
            log(cardFocus.toString());
          },
          enablePostalCode: true,
          style: CardFormStyle(
            backgroundColor: AppColors.NEUTRAL_100,
            textColor: AppColors.NEUTRAL_950,
            cursorColor: AppColors.PRIMARY_BASE,
            borderColor: Colors.transparent,
            placeholderColor: AppColors.NEUTRAL_800,
            borderWidth: 2,
          ),
        ),
        CustomButton(
          width: Get.width,
          height: 50.h,
          buttonStyle: CustomButtonStyle.ACTIVE,
          title: "Apply",
          onPressed: () async {
            if (controller.details.complete == true) {
              CardFieldInputDetails details = controller.details;

              PaymentCardModel card = PaymentCardModel(
                last4: details.last4.toString(),
                expMonth: details.expiryMonth,
                expYear: details.expiryYear,
                cardType: CardTypeExtension.fromString(details.brand),
              );

              widget.onApplyCardTap?.call(card);
            } else {
              SnackbarUtil.showError(
                  title: "Required",
                  message: "Please enter valid card details");
            }
          },
        ),
      ],
    );
 
// -------- CREATING PAYMENT METHOD.

    try {
      PaymentMethod paymentMethod = await Stripe.instance.createPaymentMethod(
        params: PaymentMethodParams.card(
          paymentMethodData: PaymentMethodData(
            billingDetails: billingDetails,
          ),
        ),
      );

      return PaymentProcessResponse(exception: null, object: paymentMethod);
    } on StripeException catch (e) {
        throw e;
    } catch (e) {
      throw e;
    }
  }
**Expected behavior**
Should return Payment Method.

**Smartphone / tablet**
 - Pixel 7 pro, Emulator
 - OS: Andriod 15
 - Package version: 11.3.0
 - Flutter version [e.g. 2.0.0.]

**Additional context**
It's perfectly working on ios but on the andriod it throws that the card details are incomplete, and exception is thrown from creatPaymentMethod catch fun.

@ignatz @spendres @cornwe19 @asaarnak

**Comment by Nikunj-Flutter** [comment]
@phawadshah any update on this issue , i am facing same error while doing this.

**Comment by phawadshah** [comment]
@Nikunj-Flutter Nothing! I used payment sheet instead.

**Comment by black10manda** [comment]
DO NOT close the card field until the payment is confirmed.

**Comment by casana9002** [comment]
Tengo el mismo problema

**Comment by MarcusHellkvist** [comment]
I have the same issue but on iOS and for me it works perfectly fine on Android!

**Comment by remonh87** [comment]
The challenge is that this error is raised by the stripe native sdk and we have little control over this. We are working currently on a sync with the latest stripe sdks so I will take a look at it there. However I would like to strongly advice to use paymentsheet as the go to for payments. Also Stripe clearly states that these elements will be minimally supported in the future in favor of the paymentsheet.

**Comment by remonh87** [comment]
This is fixed in  v12.0.0

**Comment by Kevin9597** [comment]
Yes I Also facing the issue still

This issue only comes in android in iOS working fine

LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null)

To Reproduce
Steps to reproduce the behavior:

Entering number 4242 4242 4242 4242 || 12/28 ||123 into the cardfield.
Tapping the confirm button.
Observe a failure with exception (including the part of the stack trace, belonging to this package) …
LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: Card details not complete, message: Card details not complete, stripeErrorCode: null, declineCode: null, type: null)
Expected behavior
A clear and concise description of what you expected to happen.

Smartphone / tablet

Device: [e.g. pixel 8 pro]
OS: [e.g. Android 15]
flutter_stripe: ^11.3.0
Flutter version 3.29.3
