### ISSUE TITLE
[Android] Can't put the data in the Card field, Card field blank

### ISSUE THREAD

**Issue by robyhuzwandar** [flutter-stripe/flutter_stripe#349]
**Describe the bug**
Card filed can't focus, I can't enter anything,

![image](https://user-images.githubusercontent.com/20414047/134282408-e040771c-ef92-4418-8070-ce6f9b0ab2b2.png)

it also happens with your example project

**Expected behavior**
I can input card numbers etc. normally

**Smartphone / tablet**
 - Device: Redmi Note 8 Pro
 - OS: Android 9
 - Package version: ^1.3.0
 - Flutter version: Flutter (Channel stable, 2.2.2, on macOS 11.3 20E232 darwin-x64, locale en-ID)

**Additional context**
```
E/MethodChannel#flutter/platform_views(24999): 	... 31 more
E/flutter (24999): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Binary XML file line #22: Binary XML file line #22: Error inflating class com.google.android.material.textfield.TextInputLayout, null, android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class com.google.android.material.textfield.TextInputLayout
E/flutter (24999): Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class com.google.android.material.textfield.TextInputLayout
E/flutter (24999): Caused by: java.lang.reflect.InvocationTargetException
E/flutter (24999): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/flutter (24999): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/flutter (24999): 	at android.view.LayoutInflater.createView(LayoutInflater.java:651)
E/flutter (24999): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
E/flutter (24999): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
E/flutter (24999): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:884)
E/flutter (24999): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:845)
E/flutter (24999): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:887)
E/flutter (24999): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:493)
E/flutter (24999): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
E/flutter (24999): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
E/flutter (24999): 	at com.stripe.android.databinding.CardInputWidgetBinding.inflate(CardInputWidgetBinding.java:88)
E/flutter (24999): 	at com.stripe.android.view.CardInputWidget.<init>(CardInputWidget.kt:62)
E/flutter (24999): 	at com.stripe.android.view.CardInputWidget.<init>(CardInputWidget.kt:56)
E/flutter (24999): 	at com.reactnativestripesdk.StripeSdkCardView.<init>(StripeSdkCardView.kt:35)
E/flutter (24999): 	at com.reactnativestripesdk.StripeSdkCardViewManager.createViewInstance(StripeSdkCardViewManager.kt:58)
E/flutter (24999): 	at com.flutter.stripe.StripeSdkCardPlatformView.<init>(StripeSdkCardPlatformView.kt:33)
E/flutter (24999): 	at com.flutter.stripe.StripeSdkCardPlatformViewFactory.create(StripeSdkCardPlatformViewFactory.kt:21)
E/flutter (24999): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:146)
E/flutter (24999): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:101)
E/flutter (24999): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (24999): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (24999): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (24999): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (24999): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (24999): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (24999): 	at android.os.Looper.loop(Looper.java:165)
E/flutter (24999): 	at android.app.ActivityThread.main(ActivityThread.java:6831)
E/flutter (24999): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (24999): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (24999): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
E/flutter (24999): Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
E/flutter (24999): 	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
E/flutter (24999): 	at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(ThemeEnforcement.java:213)
E/flutter (24999): 	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:148)
E/flutter (24999): 	at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:115)
E/flutter (24999): 	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:469)
E/flutter (24999): 	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:428)
E/flutter (24999): 	... 31 more
E/flutter (24999): )
E/flutter (24999): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:597
E/flutter (24999): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
E/flutter (24999): <asynchronous suspension>
E/flutter (24999): #2      AndroidViewController.create (package:flutter/src/services/plat
E/flutter (24999): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method focus on channel flutter.stripe/card_field/0)
E/flutter (24999): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (24999): <asynchronous suspension>
E/flutter (24999):
E/flutter (24999): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method onPlaceholderChanged on channel flutter.stripe/card_field/0)
E/flutter (24999): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (24999): <asynchronous suspension>
E/flutter (24999):
E/flutter (24999): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method blur on channel flutter.stripe/card_field/0)
E/flutter (24999): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (24999): <asynchronous suspension>
E/flutter (24999):
D/Surface (24999): Surface::disconnect(this=0x74d4bb5000,api=1)
D/Surface (24999): Surface::disconnect(this=0x74d4bb5000,api=-1)
D/Surface (24999): Surface::disconnect(this=0x74d4bb4000,api=1)
V/PhoneWindow(24999): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@1d8b7c3, this = DecorView@515d840[MainActivity]

```

**Comment by robyhuzwandar** [comment]
fixed

**Comment by hoangtrinhtiki** [comment]
Hi @robyhuzwandar how you fixed it? Thanks

**Comment by hoangtrinhtiki** [comment]
I can see the error `The style on this component requires your app theme to be Theme.AppCompat (or a descendant).`, but I already changed those but still cannot make it work. This only happens in some devices like my Samsung galaxy note 10+, the emulators run fine

**Comment by robyhuzwandar** [comment]
> I can see the error `The style on this component requires your app theme to be Theme.AppCompat (or a descendant).`, but I already changed those but still cannot make it work. This only happens in some devices like my Samsung galaxy note 10+, the emulators run fine

make sure to make the same your styles on values and values-night
