### ISSUE TITLE
Icon disappears from card payment method option in iOS Dark mode 

### ISSUE THREAD

**Issue by viktor-ohanyan** [flutter-stripe/flutter_stripe#421]
**Describe the bug**
Switching between payment methods leads to disappearing an icon from a card option.

**To Reproduce**
1. Go to iPhone Settings > Display & Brightness > APPEARANCE
2. Turn on Dark mode
3. Try to change payment method selection a few times

https://user-images.githubusercontent.com/1379131/139597204-ecc214ff-3929-4942-8b25-ac34161e91dd.MP4

**Expected behavior**
The icon should not disappear

**Smartphone / tablet**
 - Device: iPhone 12
 - OS: iOS 15.1
 - Package version: 2.0.1
 - Flutter version: 2.5.3

**Comment by remonh87** [comment]
This issue is fixed in the next version of this library. Looks like it was a bug in the Stripe native sdk which is updated in the next sync

**Comment by remonh87** [comment]
fixed in version 2.0.2

**Comment by viktor-ohanyan** [comment]
@viktor-ohanyan Unfortunately, we are still facing this problem in version 2.0.2.
It's not fixed.

**Comment by remonh87** [comment]
@viktor-ohanyan  that is weird because I run the example app on the iPhone (real device) with dark appearance  and couldn't reproduce it.  Do you use the simulator by any chance?

**Comment by viktor-ohanyan** [comment]
@remonh87 No, I use a real device (iPhone 12).
I forgot to mention that in the above example style attribute of payment sheet is always ThemeMode.light.
Is it the same in your example app?

**Comment by remonh87** [comment]
that was the catch indeed. I am able to reproduce it and will file a ticket for stripe.

**Comment by remonh87** [comment]
Waiting for issue: https://github.com/stripe/stripe-react-native/issues/710 to be resolved

**Comment by jamesblasco** [comment]
As this issue is out of our hands I will close it here. I opened one in the native repository where you can subscribe to check for any updates. When that bug is fixed and released in a version of the iOS StripeSDK we will update the dependency here

https://github.com/stripe/stripe-ios/issues/1911
