### ISSUE TITLE
Discover brand logo misplaced in CVC field while using CardFormField

### ISSUE THREAD

**Issue by pshanmukha** [flutter-stripe/flutter_stripe#786]
I am using CardFormField to take user card inputs and I found the discover logo in the CVC field instead of the CVC logo or symbol 

**Used Widget**
```
CardFormField(
            controller: cardFormController,
            enablePostalCode: true,
            autofocus: true,
            style: CardFormStyle(
              textColor: Colors.black,
              fontSize: 20,
              backgroundColor: Colors.white,
              borderColor: Colors.black,
              cursorColor: Colors.black,
              placeholderColor: Colors.grey,
              textErrorColor: Colors.red,
            ),
          ),
```

**Expected behavior**
I expected CVC symbol or nothing

**Smartphone / tablet**
 - Device: android emulator
 - OS: [Android 11]
 - Package version: flutter_stripe: ^3.1.0
 - Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
   Framework • revision 7e9793dee1 (3 months ago) • 2022-03-02 11:23:12 -0600
   Engine • revision bd539267b4
   Tools • Dart 2.16.1 • DevTools 2.9.2
![stripe_discover_error](https://user-images.githubusercontent.com/55737606/173563409-1c6c4c28-00ff-4867-86b0-6f5e1f5fe77e.jpg)

**Comment by jonasbark** [comment]
This will be fixed once the stripe-android package is updated to https://github.com/stripe/stripe-android/releases/tag/v20.5.0

**Comment by pshanmukha** [comment]
got flutter stripe new version still not updated!

**Comment by keanyee** [comment]
is there an ETA on this? Thanks.

**Comment by remonh87** [comment]
this should be fixed in version 4.0.0

**Comment by keanyee** [comment]
> this should be fixed in version 4.0.0

I upgraded to version 4.0.0 and I can still see the discover brand logo.

**Comment by sleewok** [comment]
> > this should be fixed in version 4.0.0
> 
> I upgraded to version 4.0.0 and I can still see the discover brand logo.

Yep, not fixed. This is really confusing for customers. Need to get this fixed ASAP.

**Comment by jonasbark** [comment]
> This is really confusing for customers
That's why this ticket is open :)

**Comment by remonh87** [comment]
can you verify if this is fixed in version 5.0.0? I couldn't reproduce it anymore

**Comment by pshanmukha** [comment]
> can you verify if this is fixed in version 5.0.0? I couldn't reproduce it anymore

I tried with version 5.0.0
but I am getting below error

```
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\stripe_android-5.0.0\android\src\main\kotlin\com\facebook\react\bridge\WritableNativeMap.java:22: error: no suitable constructor found for ReadableMap(HashMap<Object,Object>)
        super(new HashMap<>());
        ^
    constructor ReadableMap.ReadableMap(JSONObject) is not applicable
      (argument mismatch; HashMap<Object,Object> cannot be converted to JSONObject)
    constructor ReadableMap.ReadableMap(Map<String,Object>) is not applicable
      (argument mismatch; HashMap<Object,Object> cannot be converted to Map<String,Object>)
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
any solution for this?

**Comment by jonasbark** [comment]
@pshanmukha https://github.com/flutter-stripe/flutter_stripe/issues/903
